language: scala
jdk:
  - openjdk8
  
# Cache between builds
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  # This runs the template with the default parameters, and runs test within the templated app.
  - sbt test
  # Avoid cache updates between builds
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
